#First create a persistent volume on local storage

kind: PersistentVolume
apiVersion: v1
metadata:
  name: moe-pv-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    
---

#create a volume claim on local

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: moe-pv-volume
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
