apiVersion: v1
kind: Service
metadata:
  name: moe-phpmyadmin-svc
  namespace: default
  labels:
    app: moe-phpmyadmin
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
  selector:
    app: moe-phpmyadmin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: moe-phpmyadmin-deployment
  namespace: default
  labels:
    app: moe-phpmyadmin
spec:
  selector:
    matchLabels:
      app: moe-phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: moe-phpmyadmin
    spec:
      containers:
      - name: moe-phpmyadmin
        image: phpmyadmin/phpmyadmin:4.7
        env:
          - name: PMA_HOST
            value: moe-mysql-svc.default.svc.cluster.local
        ports:
          - containerPort: 80
