version: "3.2"
services:
  php:
    build: 
      context: .
    image: sreedocker123/phpschoolapp 
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass
      - MYSQL_DB=moe_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:80"
    container_name: phpschoolapp
  mysql:
    build:  
      context: ./mysql
    image: sreedocker123/schoolmysql 
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass 
      - MYSQL_DATABASE=moe_db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend:
